/**
 * This module acts as the AI Orchestrator, bridging the AI agent
 * with the GitLab and Google Cloud ecosystem via tool handlers.
 */

const gitlab = require('./services/gitlab');
const googleCloud = require('./services/googleCloud');

/**
 * handleToolCall - The main dispatcher for AI-driven actions
 * @param {string} toolName - The name of the tool the AI wants to call
 * @param {object} args - Arguments generated by the AI
 */
async function handleToolCall(toolName, args) {
  console.log(`🤖 AI Tool Call: ${toolName}`, args);
  
  switch (toolName) {
    case 'fetch_vulnerabilities':
      // Calls GitLab's Vulnerability Report API
      return await gitlab.getVulnerabilities();
      
    case 'create_secure_fix':
      // Full workflow: Create Branch -> Commit Fix -> Create Merge Request
      // This satisfies the "Automatic Remediation" requirement
      try {
        await gitlab.createBranch(args.branch_name);
        
        await gitlab.createCommit(
          args.branch_name, 
          args.commit_message, 
          args.actions
        );
        
        const mr = await gitlab.createMergeRequest(
          args.branch_name, 
          'main', 
          args.commit_message, 
          '🛡️ Root-cause fix generated by Anthropic via GitLab AI integration. \n\nThis fix addresses high-severity vulnerabilities while maintaining code efficiency.'
        );
        
        return { success: true, mr_url: mr.web_url, mr_iid: mr.iid };
      } catch (err) {
        console.error('Error creating secure fix:', err.message);
        throw err;
      }

    case 'audit_carbon_impact':
      // Uses Google Cloud Vertex AI to check sustainability
      // This satisfies the "Green Agent" requirement
      return await googleCloud.getSustainabilityAdvice(args.config_content);

    default:
      throw new Error(`Tool ${toolName} not found in current agent configuration`);
  }
}

module.exports = { handleToolCall };
